#-*- coding: utf-8 -*-

import exceptions
import unittest.TestCase

'''
class ArithmeticError(StandardError)
class AssertionError(StandardError)
class AttributeError(StandardError)
class BaseException(__builtin__.object)
class BufferError(StandardError)
class BytesWarning(Warning)
class DeprecationWarning(Warning)
class EnvironmentError(StandardError)
class EOFError(StandardError)
class Exception(BaseException)
class FloatingPointError(ArithmeticError)
class FutureWarning(Warning)
class GeneratorExit(BaseException)
class ImportError(StandardError)
class ImportWarning(Warning)
class IndentationError(SyntaxError)
class IndexError(LookupError)
class IOError(EnvironmentError)
class KeyboardInterrupt(BaseException)
class KeyError(LookupError)
class LookupError(StandardError)
class MemoryError(StandardError)
class NameError(StandardError)
class NotImplementedError(RuntimeError)
class OSError(EnvironmentError)
class OverflowError(ArithmeticError)
class PendingDeprecationWarning(Warning)
class ReferenceError(StandardError)
class RuntimeError(StandardError)
class RuntimeWarning(Warning)
class StandardError(Exception)
class StopIteration(Exception)
class SyntaxError(StandardError)
class SyntaxWarning(Warning)
class SystemError(StandardError)
class SystemExit(BaseException)
class TabError(IndentationError)
class TypeError(StandardError)
class UnboundLocalError(NameError)
class UnicodeDecodeError(UnicodeError)
class UnicodeEncodeError(UnicodeError)
class UnicodeError(ValueError)
class UnicodeTranslateError(UnicodeError)
class UnicodeWarning(Warning)
class UserWarning(Warning)
class ValueError(StandardError)
class Warning(Exception)
class WindowsError(OSError)
class ZeroDivisionError(ArithmeticError)
'''