RDB: 3
DB_ZPROXY: zproxy
MAX_CONCURRENCY: 20
INIT_VALUE: 100
WRONG_VALUE: 10000
HEADERS:
    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Encoding: gzip,deflate,sdch
    Accept-Language: en-US,en;q=0.8
    Connection: keep-alive
    Host: ''
    Referer: http://www.baidu.com
    User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.114 Safari/537.36


PROXY_SITES:
  http://www.site-digger.com/html/articles/20110516/proxieslist.html:
    rules:
      - //table[@id='proxies_table']/tbody/tr/td[1]
    proxies:
      http: ''
      https: ''

  http://pachong.org/area/short/name/cn.html:
    rules:
      - //tr[@data-type='anonymous'] | //tr[@data-type='high']
      - .//td,1,2
    proxies:
      http: ''
      https: ''

TEST_TIMEOUT: 5
TEST_SITES:
  - http://www.baidu.com
  - http://www.163.com
  - http://www.hao123.com
